### ISSUE TITLE
properly open project

### ISSUE THREAD

**Issue by nimeshc64** [mbasaglia/Qt-Color-Widgets#16]
i m new to qt can anyone give step by step how to run this project ?? i using qt 5.5

**Comment by mbasaglia** [comment]
What do you need to do?

**Comment by nimeshc64** [comment]
im try to develop colour picker in qt, iwant to add colour wheel for it

**Comment by mbasaglia** [comment]
If you want to use the color wheel into your own project:

If you have a qmake-based system add the path to INCLUDEPATH in one of the .pro or .pri files, then you'll need to also make sure the library is correctly being loaded.
You can also include color_widgets.pri, that will add the sources of the color widget library to be compiled with your project.

If you have a CMake-based system, add color widgets as a subdirectory and link ColorWidgets-qt5.

If you want to use it from Qt designer, compile and install color_widgets_designer_plugin, it should definitely work with CMake, I have not tried with qmake lately.
