### ISSUE TITLE
using the library

### ISSUE THREAD

**Issue by Bierseppi** [mbasaglia/Qt-Color-Widgets#21]
Hello,
i have 2 problems.
1. I can't install the designer Plugins, qmake wants to know what it has to do. 
2. i don't know how to use the .pri file. are there any examples?

Best regards Bierseppi

**Comment by mbasaglia** [comment]
1: Looks like when I ported the qmake plugin to cmake I removed the qmake project file and forgot to update instructions. I guess you'll have to do this now (from the main source directory:
```bash
mkdir build
cd build
cmake ..
make ColorWidgetsPlugin_install
```
2: To use the .pri, just include it in your qmake project files, see https://github.com/mbasaglia/Knotter/blob/master/src/src.pri#L24
