### ISSUE TITLE
Starting example

### ISSUE THREAD

**Issue by dlewin** [mbasaglia/Qt-Color-Widgets#24]
hi, 
I'm using Qt without designer -under Windows- and I've included the .pri that way in my .pro: 
```
SUBDIRS += \
    ../../Qt-Color-Widgets/color_widgets.pri

include(color_widgets.pri)
```

Anyway, although tried to use it I could not found out how to have it working, even with all the headers and sources included in my project as well. 

Is it possible to have a simple working example ?
thx

**Comment by mbasaglia** [comment]
Did you try with just `include(../../Qt-Color-Widgets/color_widgets.pri)`?
What errors are you getting?

**Comment by dlewin** [comment]
I didn't the way you show as I have set the Subdir.  There is no error, no warning. I've just tried to make a test with 
```
ColorPreview* CP= new ColorPreview ; 
ColorPreview->show() ;

```
which crashed the app. Hence my question about properly using these widgets

**Comment by mbasaglia** [comment]
That doesn't look correct C++, and the include I showed you should be enough in your project file to include the widgets.

**Comment by dlewin** [comment]
ok so this is the pro new lines:
```
include(../../Qt-Color-Widgets/color_widgets.pri)
unix|win32: LIBS += -L$$PWD/./ -lColorWidgets-qt51
```
But this is producing many errors like : 

> I:\Outils\Qt\5.7\mingw53_32\lib\libColorWidgets-qt51.a(d000375.o):-1: error : multiple definition of `AbstractWidgetList::count() const'
> I:\Outils\Qt\5.7\mingw53_32\lib\libColorWidgets-qt51.a(d000372.o):-1: error : multiple definition of `color_widgets::HueSlider::colorHue() const'

**Comment by mbasaglia** [comment]
You are both including the color widgets sources into your project and
linking it as a library, you need only one.

**Comment by dlewin** [comment]
Ok, I'v left only the 
`include(../../Qt-Color-Widgets/color_widgets.pri) `
line as suggested, which is still a problem:

#include  "color_wheel.hpp"
color_widgets::ColorWheel CW ;

311 Warning and errors: 

```
I:\Developements\Git_hub\Qt-Color-Widgets\src\color_preview.cpp:45: warning: 'color_widgets::ColorPreview::ColorPreview(QWidget*)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 ColorPreview::ColorPreview(QWidget *parent) :

 I:\Developements\Git_hub\CAMEL\CAMEL\camel.cpp:22: error : undefined reference to `_imp___ZN13color_widgets10ColorWheelC1EP7QWidget'
```

**Comment by dlewin** [comment]
ok,  I done another way ; instead of "pri" I've used the lib way:
`unix|win32: LIBS += -L$$PWD/./ -llibColorWidgets-qt51`
with the same previous code as before
which is now ok.....well quite ok, compiled without prob and no runtime crash. 
But nothing happens: 

> setGeometry: Unable to set geometry 100x100+640+300 on QWidgetWindow/'color_widgets::ColorWheelClassWindow'. Resulting geometry:  142x100+640+300 (frame: 9, 38, 9, 9, custom margin: 0, 0, 0, 0, minimum size: 0x0, maximum size: 16777215x16777215).

**Comment by dlewin** [comment]
my bad for the last one: this is coming because I use dockWidget and yours can not be in the centralwidget. 

Finally,  it's ok as long as I use the "_lib way_"
