### ISSUE TITLE
Hue/gradient sliders change color on click

### ISSUE THREAD

**Issue by caryoscelus** [mbasaglia/Qt-Color-Widgets#31]
Currently they use the default behaviour for slider, that is scroll in the direction of click, which is pretty counter-intuitive and inconvenient for color choosing. Better behaviour would be to immediately switch to position under mouse cursor (same as color wheel).

**Comment by mbasaglia** [comment]
I agree with this. Currently we are using the built-in QSlider input handling. If the override this, we'll need to make sure every case is handled correctly (eg: horizontal/vertical etc).
