### ISSUE TITLE
Swatch doesn't resize automatically when palette changes

### ISSUE THREAD

**Issue by caryoscelus** [mbasaglia/Qt-Color-Widgets#36]
This leads to swatch staying invisible (having zero size) even when palette is being filled, if it was originally added with an empty palette. Looks like when `sizeHint` changes, `updateGeometry()` should be called on widget.

**Comment by mbasaglia** [comment]
I don't think updateGeometry is the issue, looks like if you add colors and the Swatch has a color size policy that requires resizing, paletteModified was not being called (though I just tested this on a widget by itself, outside of a layout).

**Comment by mbasaglia** [comment]
The issues I've found are fixed in 1511046, can you check if that fixes this in you case?

**Comment by caryoscelus** [comment]
That fixed it, yeah. Thanks.
