### ISSUE TITLE
cannot convert from 'const QMetaObject *const [2]' to 'const QMetaObject::SuperData *'

### ISSUE THREAD

**Issue by Roger8** [mbasaglia/Qt-Color-Widgets#43]
windows 10
qt 5.14.2
\Qt-Color-Widgets\QtColorWidgets_autogen\include_Debug\RLEUYPZXAT/moc_color_dialog.cpp(287,69): error C2440: 'initializing': cannot convert from 'const QMetaObject *const [2]' to 'const QMetaObject::SuperData *'

**Comment by mbasaglia** [comment]
hmm, I don't think that's enough context
